main.java.com.company.dijkstratest.Pair
NAME
main.java.com.company.dijkstratest.Pair -
SYNOPSIS
Inherits Comparable< Pair >.
Public Member Functions
Pair (Vertex v, int s)
Vertex getVertex ()
void setStepNumberToInfinity ()
int getStepNumber ()
int compareTo (Pair other)
Private Attributes
Vertex vertex
int stepNumber
Detailed Description
Pair hold vertex and the steps from the vertex to all others
Author:
hzhang
Definition at line 7 of file Pair.java.
Constructor & Destructor Documentation
main.java.com.company.dijkstratest.Pair.Pair (Vertexv, ints)
Definition at line 12 of file Pair.java.
Member Function Documentation
int main.java.com.company.dijkstratest.Pair.compareTo (Pairother)
Sort Pair object
Parameters:
other
Returns:
Definition at line 38 of file Pair.java.
References main.java.com.company.dijkstratest.Pair.getStepNumber(), and main.java.com.company.dijkstratest.Pair.getVertex().
int main.java.com.company.dijkstratest.Pair.getStepNumber ()
Definition at line 28 of file Pair.java.
References main.java.com.company.dijkstratest.Pair.stepNumber.
Referenced by main.java.com.company.dijkstratest.Pair.compareTo().
Vertex main.java.com.company.dijkstratest.Pair.getVertex ()
Definition at line 18 of file Pair.java.
References main.java.com.company.dijkstratest.Pair.vertex.
Referenced by main.java.com.company.dijkstratest.Pair.compareTo().
void main.java.com.company.dijkstratest.Pair.setStepNumberToInfinity ()
Definition at line 23 of file Pair.java.
References main.java.com.company.dijkstratest.Pair.stepNumber.
Member Data Documentation
int main.java.com.company.dijkstratest.Pair.stepNumber [private]
Definition at line 10 of file Pair.java.
Referenced by main.java.com.company.dijkstratest.Pair.getStepNumber(), and main.java.com.company.dijkstratest.Pair.setStepNumberToInfinity().
Vertex main.java.com.company.dijkstratest.Pair.vertex [private]
Definition at line 9 of file Pair.java.
Referenced by main.java.com.company.dijkstratest.Pair.getVertex().
Author
Generated automatically by Doxygen for P6_LDH from the source code.