main.java.com.company.dijkstratest.Vertex
NAME
main.java.com.company.dijkstratest.Vertex -
SYNOPSIS
Inherits Comparable< Vertex >.
Public Member Functions
Vertex (String name)
int getWeight ()
void setMinDistance (int distance)
int getMinDistance ()
void setPrevious (Vertex vertex)
Vertex getPrevious ()
void setAdjacencies (Vertex...vertexList)
HashSet< Vertex > getAdjacencies ()
void setSteps (Vertex v, int integer)
ArrayList< Pair > getSteps ()
String getName ()
void setDiameter (int diameter)
int getDiameter ()
String toString ()
int compareTo (Vertex other)
void removeSteps (Vertex v)
Private Attributes
final int weight = 1
int minDistance = Integer.MAX_VALUE
Vertex previous
HashSet< Vertex > adjacencies = new HashSet<Vertex>()
ArrayList< Pair > steps = new ArrayList<Pair>()
final String name
int diameter = 0
Detailed Description
Vertex Information
Author:
hzhang
Definition at line 11 of file Vertex.java.
Constructor & Destructor Documentation
main.java.com.company.dijkstratest.Vertex.Vertex (Stringname)
Constructor Initial vertex name and default weight
Parameters:
name vertex name
Definition at line 19 of file Vertex.java.
References main.java.com.company.dijkstratest.Vertex.name.
Member Function Documentation
int main.java.com.company.dijkstratest.Vertex.compareTo (Vertexother)
Definition at line 70 of file Vertex.java.
References main.java.com.company.dijkstratest.Vertex.getName().
HashSet<Vertex> main.java.com.company.dijkstratest.Vertex.getAdjacencies ()
Definition at line 44 of file Vertex.java.
References main.java.com.company.dijkstratest.Vertex.adjacencies.
Referenced by main.java.com.company.dijkstratest.StepsMatrix.calculateShortestPath().
int main.java.com.company.dijkstratest.Vertex.getDiameter ()
Definition at line 64 of file Vertex.java.
int main.java.com.company.dijkstratest.Vertex.getMinDistance ()
Definition at line 33 of file Vertex.java.
References main.java.com.company.dijkstratest.Vertex.minDistance.
String main.java.com.company.dijkstratest.Vertex.getName ()
Definition at line 57 of file Vertex.java.
References main.java.com.company.dijkstratest.Vertex.name.
Referenced by main.java.com.company.dijkstratest.Vertex.compareTo(), and main.java.com.company.dijkstratest.Vertex.removeSteps().
Vertex main.java.com.company.dijkstratest.Vertex.getPrevious ()
Definition at line 40 of file Vertex.java.
References main.java.com.company.dijkstratest.Vertex.previous.
ArrayList<Pair> main.java.com.company.dijkstratest.Vertex.getSteps ()
Definition at line 51 of file Vertex.java.
References main.java.com.company.dijkstratest.Vertex.steps.
int main.java.com.company.dijkstratest.Vertex.getWeight ()
Definition at line 26 of file Vertex.java.
References main.java.com.company.dijkstratest.Vertex.weight.
Referenced by main.java.com.company.dijkstratest.StepsMatrix.calculateShortestPath().
void main.java.com.company.dijkstratest.Vertex.removeSteps (Vertexv)
Definition at line 72 of file Vertex.java.
References main.java.com.company.dijkstratest.Vertex.getName(), and main.java.com.company.dijkstratest.Vertex.steps.
void main.java.com.company.dijkstratest.Vertex.setAdjacencies (Vertex...vertexList)
Definition at line 43 of file Vertex.java.
void main.java.com.company.dijkstratest.Vertex.setDiameter (intdiameter)
Definition at line 63 of file Vertex.java.
References main.java.com.company.dijkstratest.Vertex.diameter.
void main.java.com.company.dijkstratest.Vertex.setMinDistance (intdistance)
Definition at line 32 of file Vertex.java.
References main.java.com.company.dijkstratest.Vertex.minDistance.
void main.java.com.company.dijkstratest.Vertex.setPrevious (Vertexvertex)
Definition at line 39 of file Vertex.java.
References main.java.com.company.dijkstratest.Vertex.previous.
void main.java.com.company.dijkstratest.Vertex.setSteps (Vertexv, intinteger)
Definition at line 50 of file Vertex.java.
String main.java.com.company.dijkstratest.Vertex.toString ()
Definition at line 67 of file Vertex.java.
References main.java.com.company.dijkstratest.Vertex.name.
Member Data Documentation
HashSet<Vertex> main.java.com.company.dijkstratest.Vertex.adjacencies = new HashSet<Vertex>() [private]
Definition at line 42 of file Vertex.java.
Referenced by main.java.com.company.dijkstratest.Vertex.getAdjacencies().
int main.java.com.company.dijkstratest.Vertex.diameter = 0 [private]
Diameter
Definition at line 62 of file Vertex.java.
Referenced by main.java.com.company.dijkstratest.Vertex.setDiameter().
int main.java.com.company.dijkstratest.Vertex.minDistance = Integer.MAX_VALUE [private]
The minimum distance
Definition at line 31 of file Vertex.java.
Referenced by main.java.com.company.dijkstratest.Vertex.getMinDistance(), and main.java.com.company.dijkstratest.Vertex.setMinDistance().
final String main.java.com.company.dijkstratest.Vertex.name [private]
Vertex name
Definition at line 56 of file Vertex.java.
Referenced by main.java.com.company.dijkstratest.Vertex.getName(), main.java.com.company.dijkstratest.Vertex.toString(), and main.java.com.company.dijkstratest.Vertex.Vertex().
Vertex main.java.com.company.dijkstratest.Vertex.previous [private]
We don't use it now
Definition at line 38 of file Vertex.java.
Referenced by main.java.com.company.dijkstratest.Vertex.getPrevious(), and main.java.com.company.dijkstratest.Vertex.setPrevious().
ArrayList<Pair> main.java.com.company.dijkstratest.Vertex.steps = new ArrayList<Pair>() [private]
Steps is an arrayList hold all steps from current vertex to all other vertices
Definition at line 49 of file Vertex.java.
Referenced by main.java.com.company.dijkstratest.Vertex.getSteps(), and main.java.com.company.dijkstratest.Vertex.removeSteps().
final int main.java.com.company.dijkstratest.Vertex.weight = 1 [private]
The weight of each vertex, now all weight is 1
Definition at line 25 of file Vertex.java.
Referenced by main.java.com.company.dijkstratest.Vertex.getWeight().
Author
Generated automatically by Doxygen for P6_LDH from the source code.