main.java.com.company.dijkstratest.StepsMatrix
NAME
main.java.com.company.dijkstratest.StepsMatrix -
SYNOPSIS
Public Member Functions
StepsMatrix (ArrayList< Vertex > vertices, ArrayList< Vertex > toBeProcessed, ArrayList< Vertex > eliminatedList)
void buildStepsMatrix ()
void calculateShortestPath (Vertex source)
float getCentrality (int diameter)
void reset (ArrayList< Vertex > vertices)
void recovery (Vertex source, int diameter)
Private Attributes
ArrayList< Vertex > vertices
ArrayList< Vertex > toBeProcessed
ArrayList< Vertex > eliminatedList
ArrayList< Vertex > beingReturned = new ArrayList<Vertex>()
int size
Detailed Description
Dijkstra: find the shortest path to vertices
Author:
hzhang
Definition at line 13 of file StepsMatrix.java.
Constructor & Destructor Documentation
main.java.com.company.dijkstratest.StepsMatrix.StepsMatrix (ArrayList< Vertex >vertices, ArrayList< Vertex >toBeProcessed, ArrayList< Vertex >eliminatedList)
Constructor
Parameters:
vertices total vertices
toBeProcessed community candidates which will be processed
eliminatedList the eliminated vertices
Definition at line 27 of file StepsMatrix.java.
References main.java.com.company.dijkstratest.StepsMatrix.eliminatedList, main.java.com.company.dijkstratest.StepsMatrix.size, main.java.com.company.dijkstratest.StepsMatrix.toBeProcessed, and main.java.com.company.dijkstratest.StepsMatrix.vertices.
Member Function Documentation
void main.java.com.company.dijkstratest.StepsMatrix.buildStepsMatrix ()
Build the steps matrix.
Definition at line 42 of file StepsMatrix.java.
References main.java.com.company.dijkstratest.StepsMatrix.beingReturned, main.java.com.company.dijkstratest.StepsMatrix.calculateShortestPath(), main.java.com.company.dijkstratest.StepsMatrix.getCentrality(), main.java.com.company.dijkstratest.StepsMatrix.recovery(), main.java.com.company.dijkstratest.StepsMatrix.reset(), main.java.com.company.dijkstratest.StepsMatrix.size, main.java.com.company.dijkstratest.StepsMatrix.toBeProcessed, and main.java.com.company.dijkstratest.StepsMatrix.vertices.
void main.java.com.company.dijkstratest.StepsMatrix.calculateShortestPath (Vertexsource)
Calculate the shortest path based on DIJKSTRA algorithm.
Parameters:
source
Definition at line 81 of file StepsMatrix.java.
References main.java.com.company.dijkstratest.Vertex.getAdjacencies(), and main.java.com.company.dijkstratest.Vertex.getWeight().
Referenced by main.java.com.company.dijkstratest.StepsMatrix.buildStepsMatrix().
float main.java.com.company.dijkstratest.StepsMatrix.getCentrality (intdiameter)
Return the centrality with two digits fractions
Parameters:
diameter
Returns:
Definition at line 109 of file StepsMatrix.java.
Referenced by main.java.com.company.dijkstratest.StepsMatrix.buildStepsMatrix().
void main.java.com.company.dijkstratest.StepsMatrix.recovery (Vertexsource, intdiameter)
put the vertices whose diameter > 10 back to the original vertices
Parameters:
source
diameter
Definition at line 132 of file StepsMatrix.java.
References main.java.com.company.dijkstratest.StepsMatrix.toBeProcessed.
Referenced by main.java.com.company.dijkstratest.StepsMatrix.buildStepsMatrix().
void main.java.com.company.dijkstratest.StepsMatrix.reset (ArrayList< Vertex >vertices)
Reset the minimum value to 0
Parameters:
vertices
Definition at line 119 of file StepsMatrix.java.
Referenced by main.java.com.company.dijkstratest.StepsMatrix.buildStepsMatrix().
Member Data Documentation
ArrayList<Vertex> main.java.com.company.dijkstratest.StepsMatrix.beingReturned = new ArrayList<Vertex>() [private]
Definition at line 18 of file StepsMatrix.java.
Referenced by main.java.com.company.dijkstratest.StepsMatrix.buildStepsMatrix().
ArrayList<Vertex> main.java.com.company.dijkstratest.StepsMatrix.eliminatedList [private]
Definition at line 17 of file StepsMatrix.java.
Referenced by main.java.com.company.dijkstratest.StepsMatrix.StepsMatrix().
int main.java.com.company.dijkstratest.StepsMatrix.size [private]
Definition at line 19 of file StepsMatrix.java.
Referenced by main.java.com.company.dijkstratest.StepsMatrix.buildStepsMatrix(), and main.java.com.company.dijkstratest.StepsMatrix.StepsMatrix().
ArrayList<Vertex> main.java.com.company.dijkstratest.StepsMatrix.toBeProcessed [private]
Definition at line 16 of file StepsMatrix.java.
Referenced by main.java.com.company.dijkstratest.StepsMatrix.buildStepsMatrix(), main.java.com.company.dijkstratest.StepsMatrix.recovery(), and main.java.com.company.dijkstratest.StepsMatrix.StepsMatrix().
ArrayList<Vertex> main.java.com.company.dijkstratest.StepsMatrix.vertices [private]
Definition at line 15 of file StepsMatrix.java.
Referenced by main.java.com.company.dijkstratest.StepsMatrix.buildStepsMatrix(), and main.java.com.company.dijkstratest.StepsMatrix.StepsMatrix().
Author
Generated automatically by Doxygen for P6_LDH from the source code.