main.java.com.company.dijkstratest.ConnectionMatrix
NAME
main.java.com.company.dijkstratest.ConnectionMatrix -
SYNOPSIS
Public Member Functions
ConnectionMatrix (ArrayList< Vertex > vertices, ArrayList< String > adjacencyList)
void buildConnectionMatrix ()
void registerAdjacenciesToEachVertex ()
String[] splitOpCp (String opCp)
void fillGrid ()
void displayConnectionMatrix ()
Private Attributes
final ArrayList< String > adjacencyList
final ArrayList< Vertex > vertices
final ArrayList< ArrayList
< Integer > > matrix = new ArrayList<ArrayList<Integer>>()"
Detailed Description
Find the neighbor-relationship among all subscribers, and then build a connection matrix based on the neighborhood relationship
Author:
hzhang
Definition at line 11 of file ConnectionMatrix.java.
Constructor & Destructor Documentation
main.java.com.company.dijkstratest.ConnectionMatrix.ConnectionMatrix (ArrayList< Vertex >vertices, ArrayList< String >adjacencyList)
Constructor
Parameters:
subscribersList list of all subscribers
adjacencyList list of all neighbors
Definition at line 23 of file ConnectionMatrix.java.
References main.java.com.company.dijkstratest.ConnectionMatrix.adjacencyList, and main.java.com.company.dijkstratest.ConnectionMatrix.vertices.
Member Function Documentation
void main.java.com.company.dijkstratest.ConnectionMatrix.buildConnectionMatrix ()
Definition at line 29 of file ConnectionMatrix.java.
References main.java.com.company.dijkstratest.ConnectionMatrix.displayConnectionMatrix(), main.java.com.company.dijkstratest.ConnectionMatrix.fillGrid(), and main.java.com.company.dijkstratest.ConnectionMatrix.registerAdjacenciesToEachVertex().
void main.java.com.company.dijkstratest.ConnectionMatrix.displayConnectionMatrix ()
Definition at line 98 of file ConnectionMatrix.java.
References main.java.com.company.dijkstratest.ConnectionMatrix.matrix.
Referenced by main.java.com.company.dijkstratest.ConnectionMatrix.buildConnectionMatrix().
void main.java.com.company.dijkstratest.ConnectionMatrix.fillGrid ()
Build the Connection matrix base on the choose subscriber's neighborhood info with other subscribers
Definition at line 77 of file ConnectionMatrix.java.
References main.java.com.company.dijkstratest.ConnectionMatrix.vertices.
Referenced by main.java.com.company.dijkstratest.ConnectionMatrix.buildConnectionMatrix().
void main.java.com.company.dijkstratest.ConnectionMatrix.registerAdjacenciesToEachVertex ()
Definition at line 37 of file ConnectionMatrix.java.
References main.java.com.company.dijkstratest.ConnectionMatrix.adjacencyList, main.java.com.company.dijkstratest.ConnectionMatrix.splitOpCp(), and main.java.com.company.dijkstratest.ConnectionMatrix.vertices.
Referenced by main.java.com.company.dijkstratest.ConnectionMatrix.buildConnectionMatrix().
String [] main.java.com.company.dijkstratest.ConnectionMatrix.splitOpCp (StringopCp)
Split the 'op-cp' form, and put op and cp into an array
Parameters:
opCp the 'op-cp' String
Returns:
an array holds both op and cp
Definition at line 67 of file ConnectionMatrix.java.
Referenced by main.java.com.company.dijkstratest.ConnectionMatrix.registerAdjacenciesToEachVertex().
Member Data Documentation
final ArrayList<String> main.java.com.company.dijkstratest.ConnectionMatrix.adjacencyList [private]
Definition at line 13 of file ConnectionMatrix.java.
Referenced by main.java.com.company.dijkstratest.ConnectionMatrix.ConnectionMatrix(), and main.java.com.company.dijkstratest.ConnectionMatrix.registerAdjacenciesToEachVertex().
final ArrayList<ArrayList<Integer> > main.java.com.company.dijkstratest.ConnectionMatrix.matrix = new ArrayList<ArrayList<Integer>>() [private]
Definition at line 15 of file ConnectionMatrix.java.
Referenced by main.java.com.company.dijkstratest.ConnectionMatrix.displayConnectionMatrix().
final ArrayList<Vertex> main.java.com.company.dijkstratest.ConnectionMatrix.vertices [private]
Definition at line 14 of file ConnectionMatrix.java.
Referenced by main.java.com.company.dijkstratest.ConnectionMatrix.ConnectionMatrix(), main.java.com.company.dijkstratest.ConnectionMatrix.fillGrid(), and main.java.com.company.dijkstratest.ConnectionMatrix.registerAdjacenciesToEachVertex().
Author
Generated automatically by Doxygen for P6_LDH from the source code.