main.java.com.company.dijkstratest.Community
NAME
main.java.com.company.dijkstratest.Community -
SYNOPSIS
Public Member Functions
Community (ArrayList< Vertex > vertices, ArrayList< Vertex > toBeProcessed, ArrayList< Vertex > eliminatedList)
ArrayList< Vertex > buildCommunity ()
Vertex getHighestCentralitied ()
ArrayList< Vertex > getCommunityCandidates (Vertex highest)
void deleteCandidates (ArrayList< Vertex > cCandidates)
boolean isIsolated (Vertex v)
Private Member Functions
void resetSteps ()
Private Attributes
ArrayList< Vertex > vertices
ArrayList< Vertex > toBeProcessed
ArrayList< Vertex > eliminatedList
ArrayList< Pair > steps
Detailed Description
Community is to find all the community candidates
Author:
hzhang
Definition at line 10 of file Community.java.
Constructor & Destructor Documentation
main.java.com.company.dijkstratest.Community.Community (ArrayList< Vertex >vertices, ArrayList< Vertex >toBeProcessed, ArrayList< Vertex >eliminatedList)
Definition at line 17 of file Community.java.
References main.java.com.company.dijkstratest.Community.eliminatedList, main.java.com.company.dijkstratest.Community.resetSteps(), main.java.com.company.dijkstratest.Community.toBeProcessed, and main.java.com.company.dijkstratest.Community.vertices.
Member Function Documentation
ArrayList<Vertex> main.java.com.company.dijkstratest.Community.buildCommunity ()
Build Community
Definition at line 29 of file Community.java.
References main.java.com.company.dijkstratest.Community.deleteCandidates(), main.java.com.company.dijkstratest.Community.getCommunityCandidates(), main.java.com.company.dijkstratest.Community.getHighestCentralitied(), and main.java.com.company.dijkstratest.Community.toBeProcessed.
void main.java.com.company.dijkstratest.Community.deleteCandidates (ArrayList< Vertex >cCandidates)
Delete community candidates from the original vertices
Parameters:
cCandidates
Definition at line 84 of file Community.java.
Referenced by main.java.com.company.dijkstratest.Community.buildCommunity().
ArrayList<Vertex> main.java.com.company.dijkstratest.Community.getCommunityCandidates (Vertexhighest)
Get the vertices which belong to the community
Parameters:
highest
Returns:
Definition at line 65 of file Community.java.
References main.java.com.company.dijkstratest.Community.steps.
Referenced by main.java.com.company.dijkstratest.Community.buildCommunity().
Vertex main.java.com.company.dijkstratest.Community.getHighestCentralitied ()
Get the vertex which has the highest centrality/smallest diameter
Returns:
highest vertex
Definition at line 43 of file Community.java.
References main.java.com.company.dijkstratest.Community.isIsolated(), and main.java.com.company.dijkstratest.Community.vertices.
Referenced by main.java.com.company.dijkstratest.Community.buildCommunity().
boolean main.java.com.company.dijkstratest.Community.isIsolated (Vertexv)
Checking whether a vertex is isolated If it is, it will not be chosen as a highest centrality vertex.
Parameters:
v
Returns:
Definition at line 101 of file Community.java.
Referenced by main.java.com.company.dijkstratest.Community.getHighestCentralitied().
void main.java.com.company.dijkstratest.Community.resetSteps () [private]
Set the steps to the eliminated vertex to be INFINITY.
Definition at line 123 of file Community.java.
References main.java.com.company.dijkstratest.Community.eliminatedList, and main.java.com.company.dijkstratest.Community.vertices.
Referenced by main.java.com.company.dijkstratest.Community.Community().
Member Data Documentation
ArrayList<Vertex> main.java.com.company.dijkstratest.Community.eliminatedList [private]
Definition at line 14 of file Community.java.
Referenced by main.java.com.company.dijkstratest.Community.Community(), and main.java.com.company.dijkstratest.Community.resetSteps().
ArrayList<Pair> main.java.com.company.dijkstratest.Community.steps [private]
Definition at line 15 of file Community.java.
Referenced by main.java.com.company.dijkstratest.Community.getCommunityCandidates().
ArrayList<Vertex> main.java.com.company.dijkstratest.Community.toBeProcessed [private]
Definition at line 13 of file Community.java.
Referenced by main.java.com.company.dijkstratest.Community.buildCommunity(), and main.java.com.company.dijkstratest.Community.Community().
ArrayList<Vertex> main.java.com.company.dijkstratest.Community.vertices [private]
Definition at line 12 of file Community.java.
Referenced by main.java.com.company.dijkstratest.Community.Community(), main.java.com.company.dijkstratest.Community.getHighestCentralitied(), and main.java.com.company.dijkstratest.Community.resetSteps().
Author
Generated automatically by Doxygen for P6_LDH from the source code.