.TH "test.java.com.company.dijkstratest.AppTest" 3 "Tue Dec 17 2013" "Version 1.0" "P6_LDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test.java.com.company.dijkstratest.AppTest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits TestCase\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAppTest\fP (String testName)"
.br
.ti -1c
.RI "void \fBtestApp\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static Test \fBsuite\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Unit test for simple App\&. 
.PP
Definition at line 10 of file AppTest\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "test\&.java\&.com\&.company\&.dijkstratest\&.AppTest\&.AppTest (StringtestName)"
Create the test case
.PP
\fBParameters:\fP
.RS 4
\fItestName\fP name of the test case 
.RE
.PP

.PP
Definition at line 18 of file AppTest\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "static Test test\&.java\&.com\&.company\&.dijkstratest\&.AppTest\&.suite ()\fC [static]\fP"

.PP
\fBReturns:\fP
.RS 4
the suite of tests being tested 
.RE
.PP

.PP
Definition at line 26 of file AppTest\&.java\&.
.SS "void test\&.java\&.com\&.company\&.dijkstratest\&.AppTest\&.testApp ()"
Rigourous Test :-) 
.PP
Definition at line 34 of file AppTest\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for P6_LDH from the source code\&.
